version: '3'

services:
  mkdocs:
    image: amirmkh/welkinops:latest
    container_name: welkinops-docs
    restart: unless-stopped
    ports:
      - "127.0.0.1:8006:80" 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    restart: unless-stopped
    ports:
      - "127.0.0.1:4180:4180"
    env_file:
      - .env
    volumes:
      - ./emails.txt:/etc/oauth2-proxy/emails.txt

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 60

