services:
  mkdocs:
    image: git.ecorp.kalekabab.ir/amdukf/welkinops:latest
    container_name: welkinops-docs
    restart: unless-stopped
    ports:
      - "127.0.0.1:8006:80"
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=true"
    #   - "com.centurylinklabs.watchtower.scope=registryA"
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.14.0
    container_name: oauth2-proxy
    restart: unless-stopped
    ports:
      - "127.0.0.1:4180:4180"
    env_file:
      - .env
    volumes:
      - welkinops-config:/etc/oauth2-proxy

volumes:
  welkinops-config:
    external: false
