name: Build and Publish MkDocs Docker Image for Gitea

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'infra/mkdocs-configs/mkdocs-ecorp.yml'
      - '.gitea/workflows/docker-publish.yml'
      - 'infra/dockerfiles/Dockerfile.ecorp'
      - 'infra/compose-files/docker-compose-ecorp.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo manually
        run: |
          git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.GIT_AD }}/amdukf/welkinops.git
      
      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login \
            ${{ secrets.REGISTRY_URL }} \
            -u ${{ secrets.REGISTRY_USERNAME }} \
            --password-stdin

      - name: Build image
        run: |
          cd welkinops
          docker build -f infra/dockerfiles/Dockerfile.ecorp -t ${{ secrets.REGISTRY_URL }}/amdukf/welkinops:latest .

      - name: Push image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/amdukf/welkinops:latest

      - name: Deploy or update
        run: |
          cd welkinops/infra/compose-files
          echo "${{ secrets.OAUTH_ENV }}" > .env
          docker volume inspect welkinops-config >/dev/null 2>&1 || docker volume create welkinops-config

          docker run --rm \
            -e OAUTH_EMAILS="${{ vars.OAUTH_EMAILS }}" \
            -v welkinops-config:/config alpine:latest sh -c '
              printf "%s\n" "$OAUTH_EMAILS" > /config/emails.txt
            '

          docker image rm ${{ secrets.REGISTRY_URL }}/amdukf/welkinops:latest || true
          docker compose -p welkinops down || true
          docker compose -f docker-compose-ecorp.yaml up --force-recreate -d

