name: Build and Publish MkDocs Docker Image on Gitea

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.gitea/workflows/docker-publish.yml'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        run: |
          git clone http://${{ secrets.GITEA_REGISTRY_URL }}/amdukf/welkinops-mkdocs.git .
          git checkout main

      - name: Login to Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
          docker login ${{ secrets.REGISTRY_URL }} \
          -u ${{ secrets.REGISTRY_USERNAME }} \
          --password-stdin

      - name: Build Image
        run: |
          docker build -t ${{ secrets.GITEA_REGISTRY_URL }}/amdukf/welkinops-mkdocs:latest .

      - name: Push Image
        run: |
          docker push ${{ secrets.GITEA_REGISTRY_URL }}/amdukf/welkinops-mkdocs:latest